### PR TITLE
wide-integer integration

### PR DESCRIPTION
**Pull request by johnmcfarlane**

### CODE REVIEW

**Comment by ckormanyos** [comment]
Hi @johnmcfarlane am I supposed to be/expected to be doing anything to help? You left me an [open issue](https://github.com/ckormanyos/wide-integer/issues/91) but I did not address that. I'm not even entirely sure if we are talking about the same _wide_-_integer_?

**Comment by ckormanyos** [comment]
Hi @johnmcfarlane I'm not sure and I'm not so familiar with your code domain, but I have a vague idea in places like [this](https://github.com/johnmcfarlane/cnl/runs/4157913797?check_suite_focus=true#step:7:105) that we might need a special cast or conversion from `uintwide_t` to GCC's `__int128`?

**Comment by johnmcfarlane** [comment]
@ckormanyos merged. Thanks for all the hard work accommodating CNL.

**Comment by ckormanyos** [comment]
>  Thanks for all the hard work accommodating CNL.

Thanks for using the library and especially for helping improve it, @johnmcfarlane with many ideas including `constexpr`-ness, syntax checking, namespace shielding --- all these great suggestions. I am convinced that our cooperation has resulted in a better library (work to go) but greatly improved over what I could have done alone.

Thanks again, John. keep in touch on wide integer and cnl!

**Pull request merged**
