### PR TITLE
Half up rounding

### PR DESCRIPTION
**Pull request by johnmcfarlane**

### CODE REVIEW

**Comment by hbe72** [comment]
I move the discussion here, as probably this branch will be merged eventually.

Maybe we still should consider the naming of this rounding tag.

Please check https://en.wikipedia.org/wiki/Rounding#Rounding_to_the_nearest_integer
and compare:
https://en.wikipedia.org/wiki/Rounding#Round_half_away_from_zero
and
https://en.wikipedia.org/wiki/Rounding#Round_half_up

What we have in CNL as nearest_rounding is the former and what I'm proposing in this patch is the latter. Both of them are variants from nearest integer rounding with minor difference how the exact midpoint between two integer representable values are treated. Other values are rounded to nearest similarly. You see the difference only at negative values exactly at midpoint between two integer representable values.

For DSP and ASIC implementations the "nearest integer rounding half-up" has been important for ages due to its simplicity. In two's complement representation you do not need any comparisons to do the rounding. Just add "half" and throw away the LSB bits, thus
```cpp
return _impl::from_rep<_result>(_impl::to_rep(from+half())>>(ResultExponent-InputExponent))
```
I would otherwise be very happy with existing "nearest_rounding" implementation, but as I'm using the CNL version of the algorithm as bit exact reference to DSP implementation the negative "mid-point" values need to be rounded correctly as well.

**Comment by hbe72** [comment]
I could not find simple algorithm to support "nearest rounding half-up" in integer division, similar what is already defined for "nearest rounding tag". Thus the "nearest rounding half-up"for the time being should supported only from float to integer, float to fixed-point and fixed-point to fixed-point conversions. I may work on this and also other rounding modes as well after we get this merged.

**Comment by hbe72** [comment]
Corrected the tag as in [P0105R1](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2017/p0105r1.html#RoundMode).

I hope the osx builds do not get stuck...

**Comment by johnmcfarlane** [comment]
OS X is still failing but I think it's a problem with CNL's CI, not this PR. Here's the [master branch failing](https://travis-ci.org/johnmcfarlane/cnl/builds/617474610). Will investigate...

**Comment by johnmcfarlane** [comment]
Still working on this BTW. Hopefully will get to it this weekend.
John

**Comment by hbe72** [comment]
Yes I know, I've been following. Slow and frustrating process.
I'll rebase this as you get the osx builds back working and merged to master.
Heikki

**Comment by johnmcfarlane** [comment]
I did the honors. It's merged now, thanks!

**Comment by hbe72** [comment]
Thanks. I feel squash merge would have been better, but never mind, it's there ;)

**Comment by johnmcfarlane** [comment]
Ah yes, I agree. I tend to tidy up my commits before making the merge
request. More smaller commits make for better descriptions in git blame.
Not to worry tho. Thanks again.

**Pull request merged**
