### PR TITLE
osx build fix

### PR DESCRIPTION
**Pull request by hbe72**

### CODE REVIEW

**Comment by hbe72** [comment]
osx build fixed. But why this hangs even though all the tests pass? What are these duplicates which do not progress?

**Comment by hbe72** [comment]
I removed that pull_request trigger as it did not help. Do these "posix-conan-test" etc. without "Test " name come from somewhere else than test.yml? I'm stuck here.

**Comment by hbe72** [comment]
Ah ok, it is this: "Please remove the invalid/outdated status check in the protected branch setting of the repository settings"

**Comment by johnmcfarlane** [comment]
Thanks for fixing this

**Pull request merged**
