### PR TITLE
armv7 support

### PR DESCRIPTION
**Pull request by johnmcfarlane**

### CODE REVIEW

**Comment by elcojacobs** [comment]
`#if CNL_USE_INT128` will still give a warning about it not being defined

To prevent this warning, you could use:
`#if defined(CNL_USE_INT128) && CNL_USE_INT128`

**Comment by johnmcfarlane** [comment]
@elcojacobs are you sure? I'm seeing no such warning. When a symbol is not defined, it evaluates to false in preprocessor conditions: https://godbolt.org/z/lxItLH

**Comment by elcojacobs** [comment]
Seems to be triggered by -Wundef, which is not part of -Wall apparently in the godbolt test.

**Comment by johnmcfarlane** [comment]
Good to know. I'll take a look, thanks.

**Pull request merged**
